### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by phoe** [glv2/ironclad#1]
As the original repository is no longer maintained, the current fixes will not be included in systems like Quicklisp if there are no releases of the library.

Please consider making a release and bumping up the version number.

**Comment by fare** [comment]
Please consider opening an issue for https://github.com/quicklisp/quicklisp-projects to update its source repo for Quicklisp.

**Comment by phoe** [comment]
@fare https://github.com/quicklisp/quicklisp-projects/issues/1303
