### ISSUE TITLE
Timing attach

### ISSUE THREAD

**Issue by libre-man** [glv2/ironclad#2]
I did send this to the original (I think) maintainer of ironclad, but as he is not responding I thought I might open an issue here also.

There seems to be a timing attack in `PBKDF2-CHECK-PASSWORD`. It seems to be using mismatch to determine if the passwords are the same. However mismatch does not guarantee to run in constant time (constant time not meaning O(1) but always the same time given sequences of the same length). This way an attacker might determine the index where the passwords differ this way finding out the correct hash. A possible way to fix this issue is by writing your own constant time mismatch function.

A possible function could be:
``` common-lisp
(defun constant-mismatch (vec1 vec2)
    (declare (optimize (speed 3) (safety 0)))
    (check-type vec1 (simple-array (unsigned-byte 8)))
    (check-type vec2 (simple-array (unsigned-byte 8)))
    (loop :with res := (if (= (length vec1) (length vec2)) 0 1)
          :for el1 :across vec1
          :for el2 :across vec2
          :do (setq res (the fixnum (logior res (logxor el1 el2))))
          :finally (return (= res 0))))
```

**Comment by glv2** [comment]
In the ```pbkdf2-check-password``` function, the ```mismatch``` function is not called on the password directly, it is called on the salted hash of the password to check if ```(pbkdf2-hash-password password digest iterations salt)``` is equal to ```(pbkdf2-hash-password correct-password digest iterations salt)```.

A timing attack could indicate to an attacker the index where the hashes differ, but it wouldn't reveal anything about the correct password.

**Comment by glv2** [comment]
I added a function to compare byte arrays in constant time (commit ba125fda4af9c289dbaf9c5297f1989fee275461). It is now used instead of ```mismatch``` in ```pbkdf2-check-password```. It should allow the ```pbkdf2-check-password``` function to be used safely in more scenarios (e.g. network login).
